###
# Test api
GET http://localhost:8000/

###
# Save song
POST http://localhost:8000/musicas

{
    "nome": "Patience",
    "artista": "Guns n Roses",
    "tempo": 120
}

###
# Save song
POST http://localhost:8000/musicas

{
    "nome": "Hallellujah",
    "artista": "Pentatonix",
    "tempo": 150
}

###
# Consult song
GET http://localhost:8000/musicas


###
# Consult id
GET http://localhost:8000/musicas/1